# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='typid',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
