# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_userprofile_typid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='typid',
            field=models.CharField(max_length=30),
        ),
    ]
