# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20170902_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extras',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='regno',
            field=models.IntegerField(default=234, max_length=6),
            preserve_default=False,
        ),
    ]
