# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20170902_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='typid',
            field=models.CharField(choices=[('Mess Worker', 'Mess Worker'), ('Student', 'Student')], default='Student', max_length=30),
        ),
    ]
